Update azure-pipelines.yml for Azure Pipelines

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -10,21 +10,23 @@ pool:
   vmImage: ubuntu-latest
 
 jobs:
-- job: TestEnvironment
+- job: A
+  displayName: Job A
+  continueOnError: true # next job starts even if this one fails
   steps:
-  - bash: |
-      sudo apt-get update
-      echo "Arrancando servicio apache y verificando que este arriba"
-      sudo systemctl start apache2.service
-      echo `ps -ef | grep -i httpd`
-      echo "Se va a ejecutar el comando: ls $(htmlpath)"
-      echo `ls $(htmlpath)`
-    name: DetermineResult
-    
-- job: Bar
-  dependsOn: TestEnvironment
-  condition: eq(dependencies.Foo.outputs['DetermineResult.doThing'], 'Yes') #map doThing and check the value
+  - script: sudo apt-get update
+  - script: echo "Arrancando servicio apache y verificando que este arriba"
+  - script: sudo systemctl start apache2.service
+  - script: echo `ps -ef | grep -i httpd`
+  - script: echo "Se va a ejecutar el comando ls $(htmlpath)"
+  - script: echo `ls $(htmlpath)`
+  - script: exit 1
+
+- job: B
+  dependsOn: A
+  condition: eq(dependencies.A.result,'SucceededWithIssues') # targets the result of the previous job 
+  displayName: Job B
   steps:
-  - script: echo "Job TestEnvironment ran and doThing is Yes."
+  - script: echo Job B ran
 
 
